site_name: Funscript Editor
site_url: ''
use_directory_urls: False
docs_dir: 'docs/app/docs'
nav:
  - Home: 'index.md'
  - User Guide:
    - 'OFS Integration': 'user-guide/ofs-integration.md'
    - 'UI': 'user-guide/ui.md'
    - 'Algorithms': 'user-guide/algorithms.md'
    - 'Config': 'user-guide/config.md'
    - 'Build': 'user-guide/build.md'
