# Python Funscript Editor hyperparameter config

###########
# General #
###########

# This parameter specifies how many frames are skipped and interpolated during tracking.
# Increase this parameter to improve the processing speed on slow hardware. But higher
# values result in poorer predictions!
skip_frames: 1

# Specify the window size for the calculation of the reference value for the local min
# and max search.
avg_sec_for_local_min_max_extraction: 2.0

# Specify the maximum deviation for a min and max point in percent
local_max_min_delta_in_percent: 1.0

# Specify the minimum required frames for the tracking. Wee need this parameter to
# ensure there is at leas two strokes in the tracking result.
min_frames: 100


##############
# y-Movement #
##############

# Shift predicted top points by given frame number. Positive values delay the position
# and negative values result in an earlier position.
shift_top_points: 0

# Shift predicted bottom points by given frame number. Positive values delay the position
# and negative values result in an earlier position.
shift_bottom_points: 0

# An fix offset to the top points (positive values move the point up and negative values
# move the point down). The offset respect the user defined upper and lower limit.
top_points_offset: 5.0

# An fix offset to the bottom points (positive values move the point up and negative values
# move the point down). The offset respect the user defined upper and lower limit.
bottom_points_offset: -16.0

# Define the top threshold. All top points greater than (max - threshold) will be set to
# the specified max value. Set 0.0 to disable this function.
top_threshold: 2.5

# Define the bottom threshold. All bottom points lower than (min + threshold) will be set to
# the specified min value. Set 0.0 to disable this function.
bottom_threshold: 2.5


##############
# x-Movement #
##############

# Shift predicted left points by given frame number. Positive values delay the position
# and negative values result in an earlier position.
shift_left_points: 0

# Shift predicted right points by given frame number. Positive values delay the position
# and negative values result in an earlier position.
shift_right_points: 0

# An fix offset to the left points (positive values move the point right and negative values
# move the point left). The offset respect the user defined upper and lower limit.
left_points_offset: -10.0

# An fix offset to the right points (positive values move the point right and negative values
# move the point left). The offset respect the user defined upper and lower limit.
right_points_offset: 10.0

# Define the left threshold. All left points lower than (min + threshold) will be set to
# the specified min value. Set 0.0 to disable this function.
left_threshold: 2.5

# Define the right threshold. All right points greater than (max - threshold) will be set to
# the specified max value. Set 0.0 to disable this function.
right_threshold: 2.5
