# Python Funscript Editor hyperparameter config

# This parameter specifies how many frames are skipped and interpolated during tracking.
# Increase this parameter to improve the processing speed on slow hardware. But higher
# values result in poorer predictions!
skip_frames: 1

# Specify the window size for the calculation of the reference value for the local min
# and max search.
avg_sec_for_local_min_max_extraction: 1.9

# Specify the minimum required frames for the tracking. Wee need this parameter to
# ensure there is at leas two strokes in the tracking result.
min_frames: 120

# Shift predicted top points by given frame number. Positive values delay the position
# and negative values result in an earlier position.
shift_top_points: 0

# Shift predicted bottom points by given frame number. Positive values delay the position
# and negative values result in an earlier position.
shift_bottom_points: 0
