# video projection parameters
# Do not change any parameters here unless you know exactly what you are doing!
# For VR video filer options see: https://ffmpeg.org/ffmpeg-filters.html#v360

vr_he_180_sbs:
  name: '3D VR Video 180'
  video_filter: 'v360=input=he:in_stereo=sbs:pitch=${phi}:output=flat:d_fov=${fov}:w=${width}:h=${height}'
  parameter:
    height: 720
    width: 1240
    fov: 100
    phi: -45

vr_he_180_ou:
  name: '3D VR Video 180 (Vertical)'
  video_filter: 'v360=input=he:in_stereo=tb:pitch=${phi}:output=flat:d_fov=${fov}:w=${width}:h=${height}'
  parameter:
    height: 720
    width: 1240
    fov: 100
    phi: -45

vr_fisheye_200_sbs:
  name: '3D VR Video (Fisheye 200)'
  video_filter: 'v360=input=fisheye:in_stereo=sbs:id_fov=200:pitch=${phi}:output=flat:d_fov=${fov}:w=${width}:h=${height}'
  parameter:
    height: 720
    width: 1240
    fov: 100
    phi: -45

vr_equirect_360_ou:
  name: '3D VR Video 360 (Vertical)'
  video_filter: 'v360=input=equirect:in_stereo=tb:pitch=${phi}:output=flat:d_fov=${fov}:w=${width}:h=${height}'
  parameter:
    height: 720
    width: 1240
    fov: 100
    phi: -45

flat:
  name: '2D Video'
  video_filter: 'scale=${width}:${height}'
  parameter:
    height: 720
    width: -1
