# projection config
# do not change any parameter here!

# 3D Side-By-Side 180 Dome VR Videos
vr_he_sbs:
  video_filter: 'v360=input=he:in_stereo=sbs:pitch=${phi}:output=flat:d_fov=${fov}:w=${width}:h=${height}'
  parameter:
    height: 720
    width: 1240
    fov: 100
    phi: -45

# 2D Videos
flat:
  video_filter: 'scale=${width}:${height}'
  parameter:
    height: 720
    width: -1
