# Python Funscript Editor settings

# Enable or disable an additional step to zoom in the Video before selecting a tracking
# feature for the Woman or Men.
use_zoom: False

# Convert video in normal perspective view before apply tracking. This should improve the
# tracking at the border of videos, because there is the distortion very high.
use_equirectangular: False

# Scaling for the equirectangular preview window
equirectangular_scaling: 1.0

# Specify the tracking direction. Allowed values are `'x'` and `'y'`.
tracking_direction: 'y'

# Limit the max player speed in the tracking preview window (0 = disable limit)
max_playback_fps: 0
