# Python Funscript Editor settings

# Enable Kalman Filter
use_kalman_filter: False

# Enable or disable an additional step to zoom in the Video before selecting a tracking
# feature for the Woman or Men.
use_zoom: False

# Set the desired zoom value which will be used when the zoom function is activated.
zoom_factor: 4.0

# Limit the max player speed in the tracking preview window (0 = disable limit)
max_playback_fps: 0

# Set the preview image scaling factor. With a value of 1.0, the window should fill the height
# or width of the screen depending on the aspect ratio of the video.
preview_scaling: 0.6

# Specify the tracker algorithm. Available options are 'MIL', 'KCF', 'CSRT'.
tracker: 'CSRT'

# Specify the wav file to play when tracking finished (write 'off' to disable the sound notification)
notification_sound: 'sound_notification.wav'

# Time in milliseconds at which the tracking is stopped if the selected feature is not found
tracking_lost_time: 0

# Specify the scene detector algorithm. Available options:
# - 'CSV': load scene csv file from [PySceneDetect](https://github.com/Breakthrough/PySceneDetect) if available
# - 'CONTENT': Detects cuts using changes in colour and intensity between frames.
# - 'THRESHOLD': Detects fades in video.
scene_detector: 'CSV'
