# Python Funscript Editor settings

# Enable or disable an additional step to zoom in the Video before selecting a tracking
# feature for the Woman or Men.
use_zoom: False

# Specify the tracking direction. Allowed values are `'x'` and `'y'`.
tracking_direction: 'y'

# Limit the max player speed in the tracking preview window (0 = disable limit)
max_playback_fps: 0
