name: Create Windows Executable using Conda

#n: [push]
on:
  push:
    tags:
      - '*'

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build
          environment-file: environment.yaml
          python-version: 3.9
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          conda env export
      - name: Build
        shell: bash -l {0}
        run: |
          pyinstaller --add-data="funscript_editor/config/*;funscript_editor/config" --add-data="assets/*;." --hidden-import "pynput.keyboard._win32" --hidden-import "pynput.mouse._win32" funscript-editor.py   
      - uses: papeloto/action-zip@v1
        with:
          files: dist/funscript-editor
          recursive: true
          dest: funscript-editor.zip
