name: Create Windows Executable using Conda

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat env update --file environment.yml --name build
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Build Executable
      run: |
        C:\Miniconda\condabin\conda.bat activate build
        C:\Miniconda\condabin\conda.bat list
        C:\Miniconda\condabin\conda.bat pyinstaller --add-data="funscript_editor/config/*;funscript_editor/config" --hidden-import "pynput.keyboard._win32" --hidden-import "pynput.mouse._win32" funscript-editor.py
