name: Release MTFG OFS Extension Installer

on:
  push:
    tags:
      - '*'

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["windows-latest"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build-installer
          environment-file: ./contrib/Installer/environment.yaml
          python-version: 3.9
          auto-activate-base: false
      - name: Collect Conda Info
        shell: bash -l {0}
        run: |
          conda info
          conda env export
      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Build Installer
        shell: bash -l {0}
        working-directory: ./contrib/Installer
        run: |
          pyinstaller --add-data="assets/*;./" --noupx --onefile mtfg-ofs-extension-installer.py
      - name: Gets latest release info
        id: latest_release
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Installer
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./contrib/Installer/dist/mtfg-ofs-extension-installer.exe
          asset_name: mtfg-ofs-extension-installer.exe
          tag: ${{ github.ref }}
          overwrite: true

